name: envx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - openai=1.3.0
  - rich=13.0.0
  - click=8.1.0
  - pydantic=2.0.0
  # 开发依赖
  - pytest
  # pip依赖（如果某些包在conda中没有）
  - pip:
    - openai==1.3.0  # 某些包可能需要通过pip安装最新版本 